server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/post/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:9999/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
